### ISSUE TITLE
Error with requirements.txt for pip when using Functional test in Ubuntu 20.04.01

### ISSUE THREAD

**Issue by dncampo** [Fiware/context.Orion-LD#1462]
When installing Python packages using scrips/requirements.txt with pip for the functional test suite using the following documentation site:

[https://github.com/FIWARE/context.Orion-LD/blob/develop/doc/manuals-ld/installation-guide-functional-tests-ubuntu20.04.1.md](https://github.com/FIWARE/context.Orion-LD/blob/develop/doc/manuals-ld/installation-guide-functional-tests-ubuntu20.04.1.md)

After doing this and trying to run the scrips with:

`test/functionalTest/testHarness.sh`

the system fails with some python errors: 

```
Traceback (most recent call last):
  File "scripts/accumulator-server.py", line 39, in <module>
    from flask import Flask, request, Response
  File "/home/builder/git/context.Orion-LD/.venv/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/builder/git/context.Orion-LD/.venv/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/builder/git/context.Orion-LD/.venv/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/builder/git/context.Orion-LD/.venv/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/builder/git/context.Orion-LD/.venv/lib/python3.8/site-packages/werkzeug/urls.py)
```

**Comment by kzangeli** [comment]
The proposed fix didn't work in github actions, and, as it works just fine for me in Ubuntu 20.04, I'm assuming the problem lies elsewhere.
